### ISSUE TITLE
Cake.Sonar upgrade from 1.1.22 to 1.1.29 fails, shows below error

### ISSUE THREAD

**Issue by adison88** [cake-contrib/Cake.Sonar#112]
<html>
<body>

22-Dec-2021 20:15:40 | Error: One or more errors occurred. (Method not found: 'Boolean Cake.Core.IO.FilePath.op_Equality(Cake.Core.IO.FilePath, Cake.Core.IO.FilePath)'.)
-- | --
22-Dec-2021 20:15:40 | Method not found: 'Boolean Cake.Core.IO.FilePath.op_Equality(Cake.Core.IO.FilePath, Cake.Core.IO.FilePath)'.

</body>
</html>

**Comment by HofmeisterAn** [comment]
@adison88 Does the problem still exist? I use Cake 2.0.0 incl. Cake.Sonar 1.1.29 without any issues in different projects.

**Comment by HofmeisterAn** [comment]
I'll close this issue because it has not had recent activity. Don't hesitate to reopen it again.
