### ISSUE TITLE
Support SonarScanner for .NET Framework 4.6+

### ISSUE THREAD

**Issue by ismaelhamed** [cake-contrib/Cake.Sonar#120]
We currently use Cake.Build to build `net4.8` via `MSBuild`, and we also have SonarScanner for .NET Framework 4.6+ (`SonarScanner.MSBuild.exe`) already installed in our build machine with the latest version.

This scenario does not currently work because [line 48](https://github.com/cake-contrib/Cake.Sonar/blob/b92dd71bc884c2c8943f2b1086f0128f08ac6b97/src/Cake.Sonar/SonarRunner.cs#L48) in `SonarRunner` will always evaluate as `true` for Cake.Build 2.0 and 3.0

Would relying only in `SonarSettings.UseCoreClr` instead be an option? If so I could send a PR to fix it.

**Comment by twenzel** [comment]
You can use the .NET (Core) version of the scanner to scan your .NET Framework 4.8 project.

**Comment by ismaelhamed** [comment]
@twenzel Thanks, you are correct. I was under the wrong impression that each .NET framework would requiere a different SonnarScanner version. 

Closing this then.
