### ISSUE TITLE
Support legacy branching

### ISSUE THREAD

**Issue by philipooo** [cake-contrib/Cake.Sonar#76]
It would be nice if there was a flag to use legacy branching. We want to use the "Branching-Feature" of SonarQube, but can`t use sonar.branch.name because we don`t have the developer edition. So we need to use sonar.branch to set the branch-name.

**Comment by tomstaijen** [comment]
The plugin uses /d:sonar.branch when it detects a version below 7.
If that's does not meet your needs, can you elaborate on which edition/version you use?
Do you know the documentation of that version?
Do you know a docker image of that version i can test against?

**Comment by philipooo** [comment]
The problem is that we use version 7.3, but not the developer edition which comes with support for sonar.branch. So we still need to use the old sonar.branch.name parameter (called legacy branching in SonarQube) with the community edition.

**Comment by GeertvanHorrik** [comment]
I think this has been implemented? It works fine for me.

**Comment by mcliment** [comment]
Is this still an issue @philipooo? If so we can reopen the ticket.
