### ISSUE TITLE
Support waiting for the quality gate results

### ISSUE THREAD

**Issue by GeertvanHorrik** [cake-contrib/Cake.Sonar#95]
See this documentation:

https://docs.sonarqube.org/latest/analysis/gitlab-cicd/

I couldn't really find a way that this is already being used. For now I will add something like this:

```
        ArgumentCustomization = args => args
            .Append("/d:sonar.qualitygate.wait=true")
        });
```

**Comment by HofmeisterAn** [comment]
Is now included in version `1.1.30` (#111).
