### ISSUE TITLE
Use dotnet-sonarscanner package for dotnet core

### ISSUE THREAD

**Issue by twenzel** [cake-contrib/Cake.Sonar#96]
You might use the `dotnet-sonarscanner` package for dotnet core instead of your own `MSBuild.SonarQube.Runner.Tool`.

The advantage would be to get updates faster (direct from vendor) instead of waiting for community contributions.

**Comment by HofmeisterAn** [comment]
@twenzel I took a quick look into the implementation and noticed `CORECLR_TOOL_NAME`. You can simply add the `dotnet-sonarscanner` from SonarSource to your Cake build and set `UseCoreClr` to true. This will use the dotnet tool.

```csharp
#tool nuget:?package=dotnet-sonarscanner&version=5.0.4

var sonarBeginSettings = new SonarBeginSettings();
sonarBeginSettings.UseCoreClr = true;
// Your configuration.
```

**Comment by twenzel** [comment]
Unfortunately this does not use the dotnet tool.

`We're launching for CoreCLR with executable C:/Agents/smith04.01/_work/79/s/tools/MSBuild.SonarQube.Runner.Tool.4.8.0/tools/sonar-scanner-msbuild-4.8.0.12008-netcoreapp3.0/SonarScanner.MSBuild.dll`

**Comment by HofmeisterAn** [comment]
I'm pretty sure it does. I use it in a couple of builds e. g. [here](https://dev.azure.com/HofmeisterAn/GitHub-Testcontainers/_build/results?buildId=1929&view=logs&j=8d802004-fbbb-5f17-b73e-f23de0c1dec8&t=a49d73c9-807e-5b99-6f6e-9ae71f0cbb8e&l=26). Did you add the [package](https://github.com/HofmeisterAn/dotnet-testcontainers/blob/develop/build.cake#L1) to Cake? This is my [task](https://github.com/HofmeisterAn/dotnet-testcontainers/blob/develop/build.cake#L109).

**Comment by twenzel** [comment]
@HofmeisterAn You were right. The problem was, that I also had referenced the old MSBuild.SonarQube.Runner.Tool.
Now it's working fine, thanks,
